version: '3'

services:
  app:
    build: .
    entrypoint: 'docker-entrypoint.sh'
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    environment:
      - DATABASE_USER=cedar
      - DATABASE_PASSWORD=cedar
      - DATABASE_NAME=cedar_development
      - DATABASE_HOST=db
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_CACHE_STORE_URL=memcache
    ports:
      - 3000:3000
    depends_on:
      - db
      - memcached
      - worker
    volumes:
      - .:/cedar-app

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=cedar
      - MYSQL_PASSWORD=cedar
      - MYSQL_DATABASE=cedar_development
      - MYSQL_ROOT_PASSWORD=my-secret-password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes: 
      - db:/var/lib/mysql

  memcached:
    image: bitnami/memcached

  worker:
    build: .
    entrypoint: 'docker-entrypoint.sh'
    command: ['rake', 'jobs:work']
    environment:
      - DATABASE_USER=cedar
      - DATABASE_PASSWORD=cedar
      - DATABASE_NAME=cedar_development
      - DATABASE_HOST=db
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_CACHE_STORE_URL=memcache
    depends_on:
      - db
      - memcached
    volumes:
      - .:/cedar-app

volumes:
  db: